### ISSUE TITLE
Downloads count is not correct in Atom Package Badge.

### ISSUE THREAD

**Issue by bwklein** [asciidoctor/atom-asciidoc-image-helper#10]
If you look at the ReadMe badge for the https://atom.io/packages/asciidoc-image-helper package.  There are downloads shown on the package page, but the number shows 0 in the badge.  Probably a bad badge URL.

**Comment by ldez** [comment]
I think not, it's just big latency.

**Comment by bwklein** [comment]
That could be too. I will wait a day to see if this updates.  If it does, I will close this issue.

**Comment by bwklein** [comment]
It was a latency issue the downloads are not accurate in the badge now, but they are close and greater than zero.
