### ISSUE TITLE
Place images in folder that is the same as the filename without the extension.

### ISSUE THREAD

**Issue by bwklein** [asciidoctor/atom-asciidoc-image-helper#11]
In Middleman, there is an option to keep images in subdirectories that match the article filename.
As the file/folder name will change from file to file, it would be good to offer an option to place images in  a folder named after the filename.  This will offer a dynamic image folder name, and override the "Images Folder" setting.

This would also automatically add the folder name to the path in the image macro, unless the Append Images Folder option is disabled (enabled by default.)

**Comment by ldez** [comment]
Sadly, it's not possible disable an option.
