### ISSUE TITLE
Problem with image folder path when the document name has spaces

### ISSUE THREAD

**Issue by sergiomse** [asciidoctor/atom-asciidoc-image-helper#17]
Steps to reproduce the problem:

1. Create an asciidoc with an space in the name
2. Check 'Place images in folder that is the same as the filename' in config
3. Check 'Append imagesFolder in generated links.' in config
4. Paste an image

The url of the image will be:

`image::Asciidoc Test\Asciidoc_Test-9b7ee.png[]`

The viewer can't render the image because of the spcace in the path.

This path should be encodeURI when it was write

**Comment by PaulSolt** [comment]
What is the format of this encoding? 

    image::images/Final Brew Coffee Design.png[]

**Comment by PaulSolt** [comment]
Figured it out, `encodeURI` makes it use `%20` for spaces.

image::images/Final%20Brew%20Coffee%20Design.png[]
