### ISSUE TITLE
Target of image macro incorrect when imagesdir attribute is set

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-asciidoc-image-helper#2]
When the `imagesdir` attribute is set to a value other than blank, the image is placed into the correct location, but the target of the image macro is not correct. The target includes the value of the `imagesdir`.

Example:

``` asciidoc
= Document Title
:imagesdir: images
```

Paste an image. The image appears at the following location:

_images/test-52db5.png_

The AsciiDoc document ends up as:

``` asciidoc
= Document Title
:imagesdir: images

image::images/test-52db5.png[]
```

The image macro should be written as follows:

``` asciidoc
image::test-52db5.png[]
```

Notice that the value of the `imagesdir` is stripped away from the start of the target.

**Comment by bwklein** [comment]
If you are using the imagesdir attribute, disable the "Append Images Folder" option in the Settings.

**Comment by mojavelinux** [comment]
Thanks @bwklein!

**Comment by mojavelinux** [comment]
I wonder if the default should be disabled.

**Comment by bwklein** [comment]
There was a discussion that the default mode should assume the imagesdir attribute is not set and that the default images location should just work in both the file save location and the reference to it in the pasted image macro.
If someone does set the imagesdir attribute (which is recommended in the readme) then they disable the feature to append image location and update the folder setting if it is something other than "images".

**Comment by mojavelinux** [comment]
I finally had a chance to read the backlog in the gitter channel for context.

Ideally, the plugin would detect the `imagesdir` attribute in the document, then do the right thing. However, I realize that means either parsing the AsciiDoc or doing a crude search in the file to locate the attribute entry for `imagesdir`.

We might be able to leverage [.editorconfig](http://editorconfig.org/) to control this behavior. That way, it can be set per project and not globally in the plugin. Different projects are going to do things differently and this way we can avoid having to mess with Atom plugin settings.

**Comment by bwklein** [comment]
I like the editorconfig idea.  maybe this is another option in the settings panel if someone wants to set that up. https://atom.io/packages/editorconfig

I also don't think it should be too hard to search the top few lines of the asciidoc file for the imagesdir string.  I just haven't done that yet and would have to figure it out.

I have a document where all of the document attributes are in the top level file and none of them are set in the chapter files.  This would require the use of the manual plug-in settings.
